name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilacion
      id: compilacion
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilacion
        setup-command: ''
        command: gcc main.c funciones.c -o main
        timeout: 10
        max-score: 1
    - name: Prueba
      id: prueba
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Prueba
        setup-command: chmod +x test/test.sh
        command: "./test/test.sh"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILACION_RESULTS: "${{steps.compilacion.outputs.result}}"
        PRUEBA_RESULTS: "${{steps.prueba.outputs.result}}"
      with:
        runners: compilacion,prueba
